server :
  #URL : 'redis://dev-redis-gateway-001.ysl6gq.0001.aps1.cache.amazonaws.com:6379'
  # URL : 'redis://redis-dev-server:6378'
  URL : 'redis://redis:6379'


database :
  type : 'postgres'
  username : 'postgres'
  password : 'postgres'
  host: 'virujh-dev-database.cjxvyzcwczxh.ap-south-1.rds.amazonaws.com'
  database : 'devauth'
  port : 5432
  synchronize : false
  
JWT :
  expiresIn : 36000000
  secret : 'topSecret51'
  defaultStrategy : 'jwt'

textLocal :
  APIKey : 'ZykcD17gN0A-7D7kZfoBD4Xf9RZFG5v3shNk28WVDw'
  sender: 'TXTLCL'

virujhEmail :
  email: 'virujh.dev@gmail.com'
  pass: 'Virujh@123'
