"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CONSTANT_MSG = void 0;
exports.CONSTANT_MSG = {
    AUTH: "Auth",
    CALENDER: "Calender",
    NOREPORT: "No appointment id exist",
    ReportId: "ReportId already exist",
    Report: "Report id updated sucessfully",
    REPORTDELETE: "Report deleted Sucessfully",
    CHAT: "Chat",
    SERVICE_INACTIVE_MSG: "service is offline. Please check once",
    SERVICE_ACTIVE_MSG: "service is online",
    INVALID_CREDENTIALS: "Invalid Credentails",
    ACCOUNT_NOT_ACTIVATE: "Your account not yet activate. Please contact admin",
    DB_ERROR: "Error in Database Query",
    CONTENT_NOT_AVAILABLE: "Content Not Available",
    INVALID_MOBILE_NO: "Invalid mobile Number",
    UPDATE_FAILED: "Updation Failed",
    UPDATE_OK: "Updated Successfully",
    APPOINT_CANCELED: "Appointment Cancelled Successfully",
    DAY_OF_WEEK: "Please enter DayOfWeek Correctly",
    ALREADY_PRESENT: "Phone number already exists please login using the existing credentials",
    INVALID_REQUEST: "Invalid request",
    PHONE_EXISTS: "Phone number already exists",
    TIME_OVERLAP: "Someone has already booked this slot.Please select another.",
    APPOINT_ALREADY_CANCELLED: "Appointment already Cancelled",
    APPOINT_NOT_AVAILABLE: "Appointment is not available",
    CONFIRMATION_REQUIRED: "Confirmation Required",
    NO_PERMISSION: "No Permission",
    INVALID_PHONE: "Invalid Phone",
    INVALID_PASSWORD: "Invalid Password",
    END_TIME_MISMATCHING: "End time is mismatching with respect to doctor session timing",
    INVALID_TIMINGS: "Start time should be less than End time",
    NO_WORK_SCHEDULE: "Doctor has no work schedule on this date",
    MAIL_OK: "Mail sent successfully",
    MAIL_ERROR: "Failure to send mail",
    SMS_OK: "SMS sent successfully",
    SMS_ERROR: "Failure to send SMS",
    PAYMENT_OK: "SMS sent successfully",
    PAYMENT_ERROR: "Failure to send SMS",
    CANCEL_EXCEEDS: "Cancellation is not possible; posting date exceeds limit of days for cancellation",
    RESCHED_EXCEEDS: "Reschedule is not possible; posting date exceeds limit of days for Reschedule",
    APPOINT_ALREADY_PRESENT: "Appointment already present on this date",
    CANCEL_NOT_ALLOWED: "Patient is not allowed to cancel this appointment",
    RESCHED_NOT_ALLOWED: "Patient is not allowed to reschedule this appointment",
    SIGNATURE_NOT_MATCHED: "Signature not matched",
    SIGNATURE_VERIFIED: "Signature verified",
    NO_APPOINT_PRESENT: "No Appointment present on this date",
    DOC_REG_FAIL: "Failed to register doctor",
    ACC_NOT_FOUND: "Unable to find hospital, Please contact admin",
    DOC_REG_HOS_RES: "Other hospital Doctor cannot register in your hospital",
    NO_PRESCRIPTION: "Please add prescription",
    NO_APPOINTMENT: "Please select appointment",
    FAILED_UPDATE_APPO: "Unable update appointment",
    SUCCESS_UPDATE_APPO: "Appointment updated successfully",
    PASSWORD_UPDATION_SUCCESS: "Password updated Successfully",
    PASSWORD_UPDATION_FAILED: "Password Updation Failed",
    OTP_VERIFICATION_SUCCESS: "OTP Verification Succesfully",
    OTP_VERIFICATION_FAILED: "OTP Verification Failed",
    NO_MESSAGE_TEMPLATE: "No Message Template",
    MESSAGE_TEMPLATE_FETCH_SUCCESS: "Message Template Fetched Successfully",
    UNEXPECTED_ERROR: "Somthing went wrong, please try again later",
    FUTURE_CALLS_NOT_POSSIBLE: "You can make calls for Past 24 hrs / current sessions but not for upcoming sessions",
    DOC_IS_ANOTHER_SESSION: "The Doctor Dr.{{DoctorName}} is consultation with Another Patient, please try after some time",
    PAT_IS_ANOTHER_SESSION: "The Patient {{patientName}} is attending another Session. Please try after some time",
    DOC_NOT_AVAILABLE: "Your session is being canceled as the Doctor is busy. Try after some time!!!",
    NO_ADVERTISEMENT_LIST: "No Advertisement List",
    ADVERTISEMENT_LIST_FETCH_SUCCESS: "Advertisement List Fetched Successfully",
    ROLES: {
        DOCTOR: "DOCTOR",
        ADMIN: "ADMIN",
        DOC_ASSISTANT: "DOC_ASSISTANT",
        PATIENT: "PATIENT",
        ATTENDER: "ATTENDER"
    },
    LIVE_STATUS: {
        OFFLINE: "offline",
        ONLINE: "online",
        VIDEO_SESSION_READY: "videoSessionReady",
        IN_SESSION: "inSession",
    },
    APPOINTMENT_STATUS: {
        COMPLETED: "completed",
        PAUSED: "paused",
        NOT_COMPLETED: "notCompleted",
    },
    PAYMENT_STATUS: {
        NOT_PAID: "notPaid",
        PARTIALLY_PAID: "partiallyPaid",
        FULLY_PAID: "fullyPaid",
        REFUNDED: "refunded",
    },
    USER_NOT_FOUND: "No user registered with this email",
    MAIL: {
        FORGOT_PASSWORD: "FORGOT_PASSWORD",
        RESET_PASSWORD: "RESET_PASSWORD",
        PATIENT_REGISTRATION: "PATIENT_REGISTRATION",
        REGISTRATION_FOR_DOCTOR: "REGISTRATION_FOR_DOCTOR",
        REGISTRATION_FOR_SUB_DOCTOR: "REGISTRATION_FOR_SUB_DOCTOR",
        APPOINTMENT_CREATED: "APPOINTMENT_CREATED",
        APPOINTMENT_RESCHEDULE: "APPOINTMENT_RESCHEDULE",
        APPOINTMENT_CANCEL: "APPOINTMENT_CANCEL",
        UPDATE_DOCTOR_REGISTRATION_TO_ADMIN: "UPDATE_DOCTOR_REGISTRATION_TO_ADMIN",
        RESET_PASSWORD_THROUGH_LINK: "RESET_PASSWORD_THROUGH_LINK",
        DAILY_APPOINTMENT_REPORT: 'DAILY_APPOINTMENT_REPORT',
        UPDATE_APPOINTMENT_TO_ATTENDER: 'UPDATE_APPOINTMENT_TO_ATTENDER',
    },
    REPORT_REMAINDER: {
        ON_EVERY_APPOINTMENT: 'ON_EVERY_APPOINTMENT',
        ONCE_A_DAY: 'ONCE_A_DAY',
        NEVER: 'NEVER'
    },
    REPORT_REMAINDER_STRING: {
        ON_EVERY_APPOINTMENT: 'On Every Appointment',
        ONCE_A_DAY: 'Once a Day',
        NEVER: 'Never',
    },
    ADMIN_EMAIL_ADDRESS: {
        EMAIL: "doc-enquiry@virujh.com",
    },
    COMM_TYPE: {
        EMAIL: "Email",
        SMS: "SMS",
        ON_SCREEN: "ON_SCREEN",
    },
    APPPOINTMENT_REPORTS: {
        NO_APPID: "Please send appointment id for which you want the reports",
        SUCCESS: "Fetched report successfully",
    },
    RESCHEDULE_MAIL_HEADER: {
        COMMON_FOR_ALL: "Appointment has been Rescheduled",
        NEW_ATTENDER: "You have invited as attender for an appointment had been Rescheduled",
    },
    UPDATE_ATTENDER_MAIL_HEADER: {
        NEW_ATTENDER: "New Appointment Video call link from Virujh",
        EXISTS_ATTENDER: "You have invited for attender",
    },
    PASSWORD_CHANGED: "Password changed succesfully",
    PASSCODE_NOT_MATCHED: "Passcode not matched",
    PROVIDE_PHONE: "Provide Phone",
    NEW_PASSWORD: "Please provide new password",
    OLD_PASSWORD: "Please Provide old password",
    CONFIRM_PASSWORD: "Please Provide confirm new password",
    OLD_NEW_SAME_PASSWORD: "Old password and new password are same",
    NEW_CONFIRM_NOT_SAME_PASSWORD: "New password and confirm new password are not same",
    INVALID_PHONE_Number: "Please provide correct phone number",
    Invalid_password: "Please provide correct password",
    message: "Payment key Feteched Sucessfully",
    DOC_RESET_PASS_API: "/api/auth/doctor/checkDoctorTokenExpiry",
    PATIENT_RESET_PASS_API: "/api/auth/patient/checkExpiry",
    ATTENDER_JOIN_SESSION: "/api/calendar/joinSession",
    JOIN_SESSION_URL: "/app/join-meeting",
    DOC_APPOINTMENT_RESCHEDULE_PAGE: "/app/appointments/",
    DOC_RESET_PASS_PAGE: "/app/reset-password",
    PAT_RESET_PASS_PAGE: "/app/reset-password-patient",
    ERROR_RES_PAGE: "/app/404ErrorPage",
    PASS_ALREADY_UPDATED: "Your password already updated",
    LOGIN_PAGE: "/app/login",
    SESSION_EXPIRED: "Your session has been expired",
    INVALID_TOKEN: "Invalid token",
    PASSWORD_RESETLINK_SENT: "Reset Link sent to registered mailId",
    PAYMENT_KEY: {
        key_id: "rzp_test_yaoAQ9nmvuUZx4",
        key_secret: "tttY7AYPndi9cCEj549QkovH",
        AndroidVersion: "2.5",
    },
    SALT_ROUNDS: 10,
    EMAIL_ALREADY_PRESENT: "Email already exists please signup using the existing credentials",
    REGISTRATION_SUCCESS: "Successfully registered",
    REGISTRATION_FAILED: "Failed to register the doctor",
};
